      
spring:
  jpa:
    hibernate:
      ddl-auto: create-drop

---

spring:
  profiles: default
  jpa:
    database: HSQL
  
---

spring:
  profiles: pcf  
  jpa:
    database: HSQL
#    database: MYSQL
  
---

spring:
  profiles: pws
  jpa:
    database: POSTGRESQL
